### ISSUE TITLE
buddy.js 0.9.0 isn't on npm

### ISSUE THREAD

**Issue by callumacrae** [Semigradsky/gulp-buddy.js#6]
In c7d05f415b1fc5a35cb2f5904ebabd7c6549a916 you updated the version of buddy.js to 0.9.0, but that [isn't on npm](https://www.npmjs.com/package/buddy.js).

Now I get the following error when trying to install gulp-buddy.js:

> npm ERR! notarget No compatible version found: buddy.js@'>=0.9.0-0 <0.10.0-0'
npm ERR! notarget Valid install targets:
npm ERR! notarget ["0.0.0","0.0.1","0.1.0","0.2.0","0.2.1","0.3.0","0.4.0","0.4.1","0.4.2","0.5.0","0.5.1","0.6.0","0.6.1","0.6.2","0.7.0","0.7.1","0.8.0"]
npm ERR! notarget
npm ERR! notarget This is most likely not a problem with npm itself.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

> npm ERR! System Darwin 14.0.0
npm ERR! command "/Users/callumacrae/.nvm/v0.10.36/bin/node" "/Users/callumacrae/.nvm/v0.10.36/bin/npm" "i"
npm ERR! cwd /Users/callumacrae/Sites/lmn/lmn-gulp-tasks
npm ERR! node -v v0.10.36
npm ERR! npm -v 1.4.28
npm ERR! code ETARGET
npm ERR! not ok code 0

Would you be able to revert that change until buddy.js 0.9.0 is pushed? Cheers!

**Comment by callumacrae** [comment]
Also see https://github.com/danielstjules/buddy.js/issues/20

**Comment by Semigradsky** [comment]
buddy.js was downgraded for a while :hourglass_flowing_sand:

**Comment by callumacrae** [comment]
:disappointed: 

Would you be able to revert your change so that this plugin is usable until 0.9.0 is back?

**Comment by callumacrae** [comment]
Oh you already did! Thanks :smile:

**Comment by callumacrae** [comment]
lol it's back on npm now

**Comment by Semigradsky** [comment]
Quickly! :smile: 
buddy.js was updated

**Comment by Semigradsky** [comment]
*offtop*
@callumacrae You may be interested - [gulp task for detecting copy-pasted and structurally similar code](https://github.com/Semigradsky/jsinspect-gulp)

**Comment by callumacrae** [comment]
Looks neat. I'll look into it, but it's unlikely I'll use it—we usually pick up stuff like that in code reviews.
